version: '3.3'

services:
  frontend_dev:
    build: ./frontend_dev
    volumes:
      - ./frontend_dev/build/:/var/www/html/
    ports:
      - 5001:80

  ngingx:
    image: localhost:5000/my-nginx:1.13.1
    volumes:
      - ./website:/var/www/html
    ports:
      - 5002:80
    depends_on:
      - frontend_dev
